:hammer: Correct path to script

diff --git a/scripts/devops/run-tests b/scripts/devops/run-tests
--- a/scripts/devops/run-tests
+++ b/scripts/devops/run-tests
@@ -2,9 +2,10 @@
 
 # Set env vars used by Coveralls
 export COVERALLS_SERVICE_NAME='Azure Devops'
-export COVERALLS_REPO_TOKEN
 COVERALLS_REPO_TOKEN=$(PIPELINE_COVERALLS_REPO_TOKEN)
-./test-ci
+export COVERALLS_REPO_TOKEN
+
+./scripts/devops/test-ci
 
 if [ -n "$CUSTOM_PRID" ]; then
   export CI_PULL_REQUEST=$CUSTOM_PRID
@@ -14,6 +15,6 @@ elif [ -n "$CUSTOM_BRANCH" ]; then
 elif [ -n "$CUSTOM_TAG" ]; then
   export BRANCH=$CUSTOM_TAG
 else
-  echo 'could not determine branch' >&2
+  echo 'Could not determine branch. Exiting...' >&2
   exit 1
 fi
